//src/app/layout.tsx
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import StoreProvider from '@/components/StoreProviders';
import ThemeProvider from '@/components/ThemeProvider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Next.js Quick Start App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <div className="bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors duration-200 min-h-screen">
            <StoreProvider>
              <Navbar />
              <main className="pt-16">{children}</main>
              <Footer />
            </StoreProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
